apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dealight
resources:
- ../../base/forecast-api
- ../../base/web
- ../../base/airflow
- ../../base/mlflow
- ../../base/prometheus
- ../../base/grafana
images:
- name: asia-southeast1-docker.pkg.dev/gen-lang-client-0222711301/dealight/airflow
  newName: asia-southeast1-docker.pkg.dev/gen-lang-client-0222711301/dealight/airflow
  newTag: 710288b1af98f16452543e94ed3f1f6ec6fdce85
- name: asia-southeast1-docker.pkg.dev/gen-lang-client-0222711301/dealight/forecast-api
  newName: asia-southeast1-docker.pkg.dev/gen-lang-client-0222711301/dealight/forecast-api
  newTag: 130e53d1be7ae4b55c7c757198f2763116f8064a
- name: asia-southeast1-docker.pkg.dev/gen-lang-client-0222711301/dealight/mlflow
  newName: asia-southeast1-docker.pkg.dev/gen-lang-client-0222711301/dealight/mlflow
  newTag: 130e53d1be7ae4b55c7c757198f2763116f8064a
- name: asia-southeast1-docker.pkg.dev/gen-lang-client-0222711301/dealight/web
  newName: asia-southeast1-docker.pkg.dev/gen-lang-client-0222711301/dealight/web
  newTag: 130e53d1be7ae4b55c7c757198f2763116f8064a
