apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dealight
resources:
- ../../base/forecast-api
- ../../base/web
- ../../base/airflow
- ../../base/mlflow
- ../../base/prometheus
- ../../base/grafana
images:
- name: asia-southeast1-docker.pkg.dev/gen-lang-client-0222711301/dealight/airflow
  newName: asia-southeast1-docker.pkg.dev/gen-lang-client-0222711301/dealight/airflow
  newTag: e4a8fe90d13327cc2a24606afddc2b9262e98c42
- name: asia-southeast1-docker.pkg.dev/gen-lang-client-0222711301/dealight/forecast-api
  newName: asia-southeast1-docker.pkg.dev/gen-lang-client-0222711301/dealight/forecast-api
  newTag: e4a8fe90d13327cc2a24606afddc2b9262e98c42
- name: asia-southeast1-docker.pkg.dev/gen-lang-client-0222711301/dealight/mlflow
  newName: asia-southeast1-docker.pkg.dev/gen-lang-client-0222711301/dealight/mlflow
  newTag: e4a8fe90d13327cc2a24606afddc2b9262e98c42
- name: asia-southeast1-docker.pkg.dev/gen-lang-client-0222711301/dealight/web
  newName: asia-southeast1-docker.pkg.dev/gen-lang-client-0222711301/dealight/web
  newTag: e4a8fe90d13327cc2a24606afddc2b9262e98c42
