apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml
      - alerts.yml
generatorOptions:
  disableNameSuffixHash: true
