apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: grafana-datasources
    files:
      - provisioning/datasources/prometheus.yml
  - name: grafana-dashboard-providers
    files:
      - provisioning/dashboards/dashboards.yml
  - name: grafana-dashboards
    files:
      - dashboards/sku-demand-observability.json
generatorOptions:
  disableNameSuffixHash: true
