CREATE SCHEMA IF NOT EXISTS features;

CREATE TABLE IF NOT EXISTS features.offline_sku_features (
    feature_version TEXT NOT NULL,
    as_of_date DATE NOT NULL,
    item_code TEXT NOT NULL,
    horizon SMALLINT NOT NULL CHECK (horizon BETWEEN 1 AND 56),
    target_date DATE NOT NULL,
    target_quantity DOUBLE PRECISION NOT NULL CHECK (target_quantity >= 0),
    day_of_week SMALLINT NOT NULL,
    day_of_month SMALLINT NOT NULL,
    week_of_year SMALLINT NOT NULL,
    month SMALLINT NOT NULL,
    quarter SMALLINT NOT NULL,
    is_weekend BOOLEAN NOT NULL,
    is_month_start BOOLEAN NOT NULL,
    is_month_end BOOLEAN NOT NULL,
    lag_1 DOUBLE PRECISION,
    lag_7 DOUBLE PRECISION,
    lag_14 DOUBLE PRECISION,
    lag_28 DOUBLE PRECISION,
    lag_56 DOUBLE PRECISION,
    rolling_mean_7 DOUBLE PRECISION,
    rolling_mean_14 DOUBLE PRECISION,
    rolling_mean_28 DOUBLE PRECISION,
    rolling_mean_56 DOUBLE PRECISION,
    rolling_std_7 DOUBLE PRECISION,
    rolling_std_28 DOUBLE PRECISION,
    rolling_min_28 DOUBLE PRECISION,
    rolling_max_28 DOUBLE PRECISION,
    rolling_sum_7 DOUBLE PRECISION,
    rolling_sum_28 DOUBLE PRECISION,
    sku_avg_sales DOUBLE PRECISION,
    sku_median_sales DOUBLE PRECISION,
    sku_sales_std DOUBLE PRECISION,
    sku_total_sales DOUBLE PRECISION,
    sku_nonzero_sales_ratio DOUBLE PRECISION,
    sku_return_rate DOUBLE PRECISION,
    sku_first_sale_date DATE,
    sku_lifecycle_days INTEGER,
    avg_unit_price DOUBLE PRECISION,
    lag_price_1 DOUBLE PRECISION,
    rolling_price_mean_7 DOUBLE PRECISION,
    rolling_price_mean_28 DOUBLE PRECISION,
    price_change_rate DOUBLE PRECISION,
    discount_proxy DOUBLE PRECISION,
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (feature_version, as_of_date, item_code, horizon),
    CHECK (target_date > as_of_date)
);

CREATE INDEX IF NOT EXISTS idx_offline_features_target_date
    ON features.offline_sku_features(feature_version, target_date);
